carpentry: swc
title: Командний рядок Unix
created: '2014-10-22'
keywords: software, data, lesson, The Carpentries
life_cycle: stable
license: CC-BY 4.0
source: https://github.com/ukrainian-carpentries/shell-novice
branch: main
contact: team@carpentries.org
episodes:
- 01-intro.md
- 02-filedir.md
- 03-create.md
- 04-pipefilter.md
- 05-loop.md
- 06-script.md
- 07-find.md
learners: ~
instructors: ~
profiles: ~
url: https://ukrainian-carpentries.github.io/shell-novice
analytics: carpentries
lang: uk
